version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    #user: "${UID}:${GID}"
    environment:
      - PORT=5000
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    user: "${UID}:${GID}"
    environment:
      - REACT_APP_API_URL=http://localhost:5000

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: